Repository SR-PLUM/SolRising, pull requests merged in 2024-05, with the labels that each got.

#35 Develop item
  Config/DefaultInput.ini
  Content/Blueprints/Character/mesh/Ch15_nonPBR_Skeleton.uasset
  Source/SolRising/Private/Character/Solaris.cpp
  Source/SolRising/Private/Item/Gun.cpp
  Source/SolRising/Private/PC_SolRising.cpp
  Source/SolRising/Private/Projectile/AmmoProjectile.cpp
  Source/SolRising/Public/Character/Solaris.h
  Source/SolRising/Public/Item/Gun.h
  Source/SolRising/Public/PC_SolRising.h
Labels: bug

#34 Develop animation
  Config/DefaultInput.ini
  Content/Blueprints/Character/ABP_Solaris_MainState.uasset
  Content/Blueprints/Character/BP_Solaris.uasset
  Content/Blueprints/Character/animation/4way_Prone_Movement.uasset
  Content/Blueprints/Character/animation/Crawl_Backwards_In_Prone.uasset
  Content/Blueprints/Character/animation/Fast_Run.uasset
  Content/Blueprints/Character/animation/FireMontage.uasset
  Content/Blueprints/Character/animation/Firing_Rifle.uasset
  Content/Blueprints/Character/animation/Jumping_Down.uasset
  Content/Blueprints/Character/animation/Prone_Forward.uasset
  Content/Blueprints/Character/animation/Prone_Idle.uasset
  Content/Blueprints/Character/animation/Prone_Left_Turn.uasset
  Content/Blueprints/Character/animation/Prone_Right_Turn.uasset
  Content/Blueprints/Character/animation/Rifle_Aim_Run.uasset
  Content/Blueprints/Character/animation/Rifle_Aiming_Idle.uasset
  Content/Blueprints/Character/animation/Rifle_Down_To_Aim.uasset
  Content/Blueprints/Character/animation/Rifle_Kneel_Idle.uasset
  Content/Blueprints/Character/animation/Run_Backward.uasset
  Content/Blueprints/Character/animation/Run_Backward_Left.uasset
  Content/Blueprints/Character/animation/Run_Backward_Right.uasset
  Content/Blueprints/Character/animation/Run_Forward.uasset
  Content/Blueprints/Character/animation/Run_Forward_Left.uasset
  Content/Blueprints/Character/animation/Run_Forward_Right.uasset
  Content/Blueprints/Character/animation/Run_Left.uasset
  Content/Blueprints/Character/animation/Run_Right.uasset
  Content/Blueprints/UI/WBP_Inventory.uasset
  Content/Blueprints/UI/WBP_ItemWidget.uasset
  Content/Sounds/FireSound.uasset
  Content/Sounds/FootSound.uasset
  Content/Sounds/LandingSound.uasset
  SolRising.uproject
  Source/SolRising/Private/Character/Solaris.cpp
  Source/SolRising/Private/Character/SolarisAnimInstance.cpp
  Source/SolRising/Private/Item/Ammo.cpp
  Source/SolRising/Private/Item/Bag.cpp
  Source/SolRising/Private/Item/Gun.cpp
  Source/SolRising/Private/PC_SolRising.cpp
  Source/SolRising/Private/UI/Inventory.cpp
  Source/SolRising/Private/UI/ItemWidget.cpp
  Source/SolRising/Public/Character/Solaris.h
  Source/SolRising/Public/Character/SolarisAnimInstance.h
  Source/SolRising/Public/Item/Item.h
  Source/SolRising/Public/PC_SolRising.h
  Source/SolRising/Public/UI/Inventory.h
  Source/SolRising/Public/UI/ItemWidget.h
Labels: enhancement

#38 Develop item
  Config/DefaultEngine.ini
  Content/Blueprints/Character/BP_Solaris.uasset
  Content/Blueprints/Item/BP_Ammo.uasset
  Content/Blueprints/Item/BP_Bag.uasset
  Content/Blueprints/Item/BP_BulletproofVest.uasset
  Content/Blueprints/Item/BP_Gun.uasset
  Content/Blueprints/Projectile/BP_AmmoProjectile.uasset
  Content/__ExternalActors__/ThirdPerson/Maps/ThirdPersonMap/0/SP/4IHNXUTCT81EY0BGIBP51H.uasset
  Content/__ExternalActors__/ThirdPerson/Maps/ThirdPersonMap/0/ZC/6IVIKED7RP64E1RGQ34VFY.uasset
  Content/__ExternalActors__/ThirdPerson/Maps/ThirdPersonMap/1/BN/DJBAVQVMHJNGC7AC3X4EKG.uasset
  Content/__ExternalActors__/ThirdPerson/Maps/ThirdPersonMap/1/OW/1FK0QEGF1CQ5U9MUZK67F2.uasset
  Content/__ExternalActors__/ThirdPerson/Maps/ThirdPersonMap/4/CO/IC801DMC3AMUEPXSEG68N7.uasset
  Content/__ExternalActors__/ThirdPerson/Maps/ThirdPersonMap/8/IJ/MKAHFK860AEYL2PGAUP1AL.uasset
  Source/SolRising/Private/Character/Solaris.cpp
  Source/SolRising/Private/Item/BulletproofVest.cpp
  Source/SolRising/Private/Projectile/AmmoProjectile.cpp
  Source/SolRising/Public/Character/Solaris.h
  Source/SolRising/Public/Item/BulletproofVest.h
Labels: bug, enhancement

#43 [Update] HealItem
  Content/Blueprints/Item/BP_HealItem.uasset
  Source/SolRising/Private/Character/Solaris.cpp
  Source/SolRising/Private/Item/BulletproofVest.cpp
  Source/SolRising/Private/Item/HealItem.cpp
  Source/SolRising/Private/Projectile/AmmoProjectile.cpp
  Source/SolRising/Public/Character/Solaris.h
  Source/SolRising/Public/Item/HealItem.h
  Source/SolRising/Public/Projectile/AmmoProjectile.h
Labels: enhancement

#42 Develop inventory
  Content/Blueprints/UI/AK_47.png
  Content/Blueprints/UI/AK_47.uasset
  Content/Blueprints/UI/AK_74U.png
  Content/Blueprints/UI/AK_74U.uasset
  Content/Blueprints/UI/M_416.png
  Content/Blueprints/UI/M_416.uasset
  Content/Blueprints/UI/WBP_GunSlot.uasset
  Content/Blueprints/UI/WBP_Inventory.uasset
  Source/SolRising/Private/Character/Solaris.cpp
  Source/SolRising/Private/Item/Gun.cpp
  Source/SolRising/Private/UI/GunSlot.cpp
  Source/SolRising/Private/UI/Inventory.cpp
  Source/SolRising/Private/UI/ItemWidget.cpp
  Source/SolRising/Public/Character/Solaris.h
  Source/SolRising/Public/Item/Gun.h
  Source/SolRising/Public/UI/GunSlot.h
  Source/SolRising/Public/UI/Inventory.h
  Source/SolRising/Public/UI/ItemWidget.h
Labels: enhancement

#46 [Update] Add Material
  .gitignore
  Content/OldWest/Shared/Materials/MF_Detail_Normal_01a.uasset
  Content/OldWest/Shared/Materials/MF_Normal_Intensity_01a.uasset
  Content/OldWest/Shared/Materials/MI_Demo_Floor_01a.uasset
  Content/OldWest/Shared/Materials/MM_Glass_01a.uasset
  Content/OldWest/Shared/Materials/MM_MasterMaterial_01a.uasset
  Content/OldWest/Shared/Materials/MM_PP_Sharpen.uasset
  Content/OldWest/Shared/Meshes/SM_ZBackdrop_01a.uasset
  Content/OldWest/Shared/Textures/TX_Desert_01a_CUBE.uasset
  Content/OldWest/Shared/Textures/TX_Fill_01_ALB.uasset
  Content/OldWest/Shared/Textures/TX_Fill_01_NRM.uasset
  Content/OldWest/Shared/Textures/TX_Fill_01_RMA.uasset
  Content/OldWest/Shared/Textures/TX_Glass_01a_MASK.uasset
  Content/OldWest/Shared/Textures/TX_Lookup_01a_LUT.uasset
  Content/OldWest/Shared/Textures/TX_Microdetail_01a_MASK.uasset
Labels: enhancement

#48 Develop inventory
  Content/Blueprints/Item/BP_Bag.uasset
  Content/Blueprints/UI/WBP_ItemWidget.uasset
  Source/SolRising/Private/Item/Ammo.cpp
  Source/SolRising/Private/Item/Bag.cpp
  Source/SolRising/Private/Item/BulletproofVest.cpp
  Source/SolRising/Private/Item/Gun.cpp
  Source/SolRising/Private/Item/HealItem.cpp
  Source/SolRising/Private/UI/Inventory.cpp
  Source/SolRising/Public/Item/Ammo.h
  Source/SolRising/Public/Item/Bag.h
  Source/SolRising/Public/Item/BulletproofVest.h
  Source/SolRising/Public/Item/Gun.h
  Source/SolRising/Public/Item/HealItem.h
  Source/SolRising/Public/Item/Item.h
Labels: bug, enhancement
